packages:
  - apps/*
  - packages/*

catalog:
  "@astrojs/mdx": ^4.3.1
  "@astrojs/node": ^9.3.0
  "@astrojs/react": ^4.3.0
  "@astrojs/sitemap": ^3.4.2
  "@biomejs/biome": ^2.0.0
  "@radix-ui/react-dropdown-menu": ^2.1.15
  "@radix-ui/react-popover": ^1.1.14
  "@radix-ui/react-select": ^2.2.5
  "@radix-ui/react-separator": ^1.1.7
  "@radix-ui/react-slot": ^1.2.3
  "@radix-ui/react-tabs": ^1.1.12
  "@tailwindcss/vite": ^4.1.11
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6
  astro: ^5.12.4
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  lucide-react: ^0.522.0
  react: ^19.1.1
  react-day-picker: ^9.8.1
  react-dom: ^19.1.1
  rehype-katex: ^7.0.1
  remark-math: ^6.0.0
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.11
  tw-animate-css: ^1.3.6
  zod: ^3.25.76
